### ISSUE TITLE
Support for Linux syscalls

### ISSUE THREAD

**Issue by merces** [mentebinaria/fravia-bot#2]
Something like ?syscall write

One reference: https://syscalls.kernelgrok.com

**Comment by mthbernardes** [comment]
http://man7.org/linux/man-pages/man2/{SYSCALL}.2.html

**Comment by mthbernardes** [comment]
Functionality added on the follow commit
https://github.com/mentebinaria/fravia-bot/commit/0d6c366c4868b3faa53a88faf9541414fe683654
